export default {
  repo: {
    FETCH_TREE: 'FETCH_TREE',
    SET_TREE: 'SET_TREE',
    SET_REPO: 'SET_REPO',
    FETCH_REFS: 'FETCH_REFS',
    SET_REFS: 'SET_REFS',
    SET_INDEX: 'SET_INDEX',
    FETCH_INDEX: 'FETCH_INDEX',
  },
  user: {
    FETCH_USER: 'FETCH_USER',
    SET_USER: 'SET_USER',
    POST_GITHUB_PERSONAL_TOKEN: 'POST_GITHUB_PERSONAL_TOKEN',
  },
};
